"""Initial migration: users, sessions, documents, analysis_results, style_issues, audit_logs

Revision ID: d274c7e2f3b7
Revises: 
Create Date: 2025-10-22 13:08:03.674347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd274c7e2f3b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('azure_oid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_users_azure_oid'), 'users', ['azure_oid'], unique=True, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_users_email'), 'users', ['email'], unique=True, schema='compliance_agent_db')
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['compliance_agent_db.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='compliance_agent_db')
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=10), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('clean_filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('PPTX', 'PDF', name='documenttype'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_info', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('upload_path', sa.String(length=512), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['compliance_agent_db.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_documents_file_id'), 'documents', ['file_id'], unique=True, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_documents_uploaded_at'), 'documents', ['uploaded_at'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_documents_user_id'), 'documents', ['user_id'], unique=False, schema='compliance_agent_db')
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['compliance_agent_db.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_sessions_token'), 'sessions', ['token'], unique=True, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='compliance_agent_db')
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('grammar_issues', sa.Integer(), nullable=True),
    sa.Column('tone_issues', sa.Integer(), nullable=True),
    sa.Column('issues_with_suggestions', sa.Integer(), nullable=True),
    sa.Column('severity_breakdown', sa.JSON(), nullable=True),
    sa.Column('category_breakdown', sa.JSON(), nullable=True),
    sa.Column('rule_breakdown', sa.JSON(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_elements', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['compliance_agent_db.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_analysis_results_created_at'), 'analysis_results', ['created_at'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_analysis_results_document_id'), 'analysis_results', ['document_id'], unique=False, schema='compliance_agent_db')
    op.create_table('style_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('GRAMMAR', 'TONE', 'STYLE', 'FORMATTING', 'CONTENT', name='issuecategory'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='issueseverity'), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('element_type', sa.String(length=50), nullable=True),
    sa.Column('element_index', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['compliance_agent_db.analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance_agent_db'
    )
    op.create_index(op.f('ix_compliance_agent_db_style_issues_analysis_id'), 'style_issues', ['analysis_id'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_style_issues_category'), 'style_issues', ['category'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_style_issues_rule_name'), 'style_issues', ['rule_name'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_style_issues_severity'), 'style_issues', ['severity'], unique=False, schema='compliance_agent_db')
    op.create_index(op.f('ix_compliance_agent_db_style_issues_slide_number'), 'style_issues', ['slide_number'], unique=False, schema='compliance_agent_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_agent_db_style_issues_slide_number'), table_name='style_issues', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_style_issues_severity'), table_name='style_issues', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_style_issues_rule_name'), table_name='style_issues', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_style_issues_category'), table_name='style_issues', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_style_issues_analysis_id'), table_name='style_issues', schema='compliance_agent_db')
    op.drop_table('style_issues', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_analysis_results_document_id'), table_name='analysis_results', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_analysis_results_created_at'), table_name='analysis_results', schema='compliance_agent_db')
    op.drop_table('analysis_results', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_sessions_user_id'), table_name='sessions', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_sessions_token'), table_name='sessions', schema='compliance_agent_db')
    op.drop_table('sessions', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_documents_user_id'), table_name='documents', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_documents_uploaded_at'), table_name='documents', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_documents_file_id'), table_name='documents', schema='compliance_agent_db')
    op.drop_table('documents', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_audit_logs_user_id'), table_name='audit_logs', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_audit_logs_created_at'), table_name='audit_logs', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_audit_logs_action'), table_name='audit_logs', schema='compliance_agent_db')
    op.drop_table('audit_logs', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_users_email'), table_name='users', schema='compliance_agent_db')
    op.drop_index(op.f('ix_compliance_agent_db_users_azure_oid'), table_name='users', schema='compliance_agent_db')
    op.drop_table('users', schema='compliance_agent_db')
    # ### end Alembic commands ###
